version: '3'
services:
  
  mysqlrouter:
    hostname: 'mysqlrouter'
    env_file:
      - mysql-router.env
    image: mysql/mysql-router:8.0
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure    
        delay: 20s
        max_attempts: 5
        window: 120s        
    ports:
      - "6446:6446"
      - "6447:6447"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure    
        delay: 20s
      placement:
        constraints: [node.role == manager]
        
networks:
  backend:
    external: true
        
