version: '2'
services:
  db1:
    image: mysql/mysql-server:5.7.25
    env_file:
      - mysql-server.env
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    volumes:
      - 'db1_data:/var/lib/mysql'
    ports:
      - "3301:3306"   
      
  db2:
    image: mysql/mysql-server:5.7.25
    env_file:
      - mysql-server.env
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    volumes:
      - 'db2_data:/var/lib/mysql'
    ports:
      - "3302:3306"   

  db3:
    image: mysql/mysql-server:5.7.25
    env_file:
      - mysql-server.env
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    volumes:
      - 'db3_data:/var/lib/mysql'
    ports:
      - "3303:3306"   
      
  mysql-shell:
    env_file:
      - mysql-shell.env
    image: neumayer/mysql-shell-batch
    volumes:
        - ./scripts/:/scripts/
    depends_on:
      - db1
      - db2
      - db3
    restart: on-failure
      
  mysql-router:
    env_file:
      - mysql-router.env
    image: mysql/mysql-router:8.0
    ports:
      - "6446:6446"
      - "6447:6447"
    depends_on:
      - db1
      - db2
      - db3
      - mysql-shell
    restart: on-failure
            
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    environment:
      - MARIADB_HOST=mysql-router
      - MARIADB_PORT_NUMBER=6446
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=mysql
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_PASSWORD=papito
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - SUITECRM_HTTP_TIMEOUT=3600
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'suitecrm_data:/bitnami'
    depends_on:
      - mysql-router
      
volumes:
  db1_data:
    driver: local
  db2_data:
    driver: local
  db3_data:
    driver: local    
  suitecrm_data:
    driver: local
