version: '2'
services:
  mariadb:
    image: mysql/mysql-server:8.0.12
    environment:
      - MYSQL_ROOT_PASSWORD=mysql    
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=bn_suitecrm
      - MYSQL_PASSWORD=papito
      - MYSQL_DATABASE=bitnami_suitecrm
#    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    volumes:
      - 'mariadb_data:/var/lib/mysql'
    ports:
      - "3306:3306"    
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=mysql
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_PASSWORD=papito
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - SUITECRM_HTTP_TIMEOUT=3600
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'suitecrm_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
