version: '3'
services:
  
  mysql-shell:
    env_file:
      - mysql-shell.env
    image: neumayer/mysql-shell-batch
    volumes:
        - ./scripts/:/scripts/
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure    
        delay: 20s
        max_attempts: 5
        window: 120s           
    depends_on:
      - db1
      - db2
      - db3
    
#  dbwebapp:
#    env_file:
#      - dbwebapp.env
#    image: neumayer/dbwebapp
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql-router
     
networks:
  backend:
    external: true
