version: '3'
services:
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: 'phpmyadmin'
    environment:
     - PMA_HOST=mysqlrouter
     - PMA_PORT=6446
    networks:
      - backend     
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure    
        delay: 20s
        max_attempts: 5
        window: 120s   
      placement:
        constraints: [node.role == manager]           
    ports:
     - 8081:80
    volumes:
     - /sessions

networks:
  backend:
    external: true
