version: '3'
services:
  
  mysql-shell:
    env_file:
      - mysql-shell.env
    image: neumayer/mysql-shell-batch
    volumes:
        - ./scripts/:/scripts/
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure    
        delay: 20s
        max_attempts: 5
        window: 120s           
    depends_on:
      - db1
      - db2
      - db3     
networks:
  backend:
    external: true
